#!/bin/bash

####################################
#Author: Amulya
#Date: 16-sep
#
#Version:v1
#
#This script will report the AWS resource usage
#####################################


set -x


#AWS S3
#AWS EC2
#AWS Lambda
#AWS IAM Users

#list s3 buckets
echo "print list of s3 buckets"
aws s3 ls > resourceTracker

#list EC2 Instances
echo "print list of EC2 instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'

#list lambda
echo "print list of lamda"
aws lambda list-functions 

#List IAM Users
echo "print list of IAM users"
aws iam list-users 
